# Generated by Django 3.0.5 on 2021-11-08 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('jsonQuestions', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Activated'), ('C', 'Closed')], default='W', max_length=1)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UI.Area')),
            ],
        ),
        migrations.CreateModel(
            name='appUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loginname', models.TextField(max_length=60, unique=True)),
                ('name', models.TextField(max_length=60)),
                ('hash', models.TextField(max_length=80)),
                ('areas', models.ManyToManyField(to='UI.Area')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
