# Generated by Django 3.0.5 on 2021-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20211124_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='globalForm',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
