# Generated by Django 3.0.5 on 2021-12-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_form_globalform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UI.Form'),
        ),
    ]
