# Generated by Django 4.0.1 on 2022-02-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_auto_20211207_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-04'),
            preserve_default=False,
        ),
    ]
