# Generated by Django 4.0.1 on 2022-02-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='submissionDate',
        ),
    ]
