# Generated by Django 4.0.1 on 2022-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0010_remove_feedback_answerdate_feedback_submissiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submissionDate',
        ),
        migrations.AddField(
            model_name='feedback',
            name='answerDate',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-04'),
            preserve_default=False,
        ),
    ]
